name: "reth"

services:
  jwt-init:
    container_name: jwt-init
    image: alpine:3.19
    volumes:
      - ./jwttoken:/jwt
    healthcheck:
      test: ["CMD", "test", "-f", "/jwt/jwt.hex"]
      interval: 5s
      timeout: 5s
      retries: 3
    command: >
      /bin/sh -c "mkdir -p /jwt && 
      if [ ! -f /jwt/jwt.hex ]; then 
        apk add --no-cache openssl &&
        openssl rand -hex 32 | tr -d '\n' > /jwt/jwt.hex; 
      fi"

  reth:
    container_name: reth
    restart: unless-stopped
    image: ghcr.io/paradigmxyz/reth:v1.1.1
    depends_on:
      jwt-init:
        condition: service_completed_successfully
    ports:
      - "9001:9001" # metrics
      - "30303:30303" # eth/66 peering
      - "8545:8545" # rpc
      - "8551:8551" # engine
    volumes:
      - mainnet_data:/root/.local/share/reth/mainnet
      - sepolia_data:/root/.local/share/reth/sepolia
      - holesky_data:/root/.local/share/reth/holesky
      - logs:/root/logs
      - ./jwttoken:/root/jwt:ro
      - ./chain:/root/chain:ro
    pid: host
    entrypoint: /bin/sh -c 
    command: 
      - |
          reth init --chain /root/chain/genesis.json
          reth node \
          --chain /root/chain/genesis.json \
          --metrics 0.0.0.0:9001 \
          --log.file.directory /root/logs \
          --authrpc.addr 0.0.0.0 \
          --authrpc.port 8551 \
          --authrpc.jwtsecret /root/jwt/jwt.hex \
          --http --http.addr 0.0.0.0 --http.port 8545 \
          --http.api "eth,net,web3,txpool" \
          --disable-discovery \
          --debug.tip 0x8bf225d50da44f60dee1c4ee6f810fe5b44723c76ac765654b6692d50459f216 \
          -vvvvv

volumes:
  mainnet_data:
    driver: local
  sepolia_data:
    driver: local
  holesky_data:
    driver: local
  logs:
    driver: local
